[package]
name = "extract-R-headers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang = { version = "1.0.3", features = ["clang_10_0", "runtime"] }
regex = "1"
